"""Mövzu (rəng, şrift, ölçü) sabitləri."""

from __future__ import annotations

# --- Brend qradiyenti (hero / CTA üçün) ---
GRADIENT_INDIGO = "#6366F1"
GRADIENT_FUCHSIA = "#D946EF"
GRADIENT_AMBER = "#F59E0B"

# --- Aksent rənglər ---
ACCENT_CYAN = "#06B6D4"
ACCENT_LIME = "#84CC16"
ACCENT_CORAL = "#F43F5E"
ACCENT_SUNFLOWER = "#FACC15"
ACCENT_VIOLET = "#8B5CF6"

# --- Tünd mövzu (standart) ---
DARK_BG_DEEPEST = "#0B0B12"
DARK_BG_BASE = "#12121A"
DARK_BG_ELEVATED = "#1B1B26"
DARK_BG_OVERLAY = "#25253A"
DARK_BORDER = "#2D2D45"
DARK_TEXT_PRIMARY = "#F4F4F8"
DARK_TEXT_SECONDARY = "#A8A8C0"
DARK_TEXT_MUTED = "#6B6B8A"

# --- Açıq mövzu ---
LIGHT_BG_BASE = "#FAFAFC"
LIGHT_BG_ELEVATED = "#FFFFFF"
LIGHT_BG_OVERLAY = "#F1F1F7"
LIGHT_BORDER = "#E5E5EE"
LIGHT_TEXT_PRIMARY = "#0B0B12"
LIGHT_TEXT_SECONDARY = "#52526B"

# --- Status rəngləri (vəziyyət rozetkaları) ---
STATUS_QUEUED = ACCENT_VIOLET
STATUS_RUNNING = ACCENT_CYAN
STATUS_DONE = ACCENT_LIME
STATUS_FAILED = ACCENT_CORAL
STATUS_CANCELLED = DARK_TEXT_MUTED

# --- Şrift ölçüləri ---
FONT_FAMILY = "Segoe UI"
FONT_MONO = "Consolas"
FS_DISPLAY = 26
FS_TITLE = 18
FS_BODY = 13
FS_SMALL = 11
FS_TINY = 10

# --- Boşluqlar ---
SPACE_XS = 4
SPACE_SM = 8
SPACE_MD = 12
SPACE_LG = 16
SPACE_XL = 24
SPACE_2XL = 32

# --- Künclər ---
RADIUS_SM = 6
RADIUS_MD = 10
RADIUS_LG = 14
RADIUS_XL = 20
